# 1.0 – Data Ingestion & Cleaning
**DATA 205 | Feraol Abera | Spring 2026**

In [ ]:
import pandas as pd
import numpy as np
import io
import os
from google.colab import files, drive

drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
BASE = '/content/drive/MyDrive/data205-project'

for folder in [
    'data/raw', 'data/interim', 'data/processed', 'data/external',
    'ingestion/notebooks', 'ingestion/docs',
    'eda/notebooks', 'eda/images', 'eda/docs',
    'analysis/notebooks', 'analysis/images', 'analysis/docs',
    'models', 'reports', 'docs'
]:
    os.makedirs(os.path.join(BASE, folder), exist_ok=True)

## Load Raw Data
Download both CSVs from the links below, then run the cells to upload them.

- Traffic Violations: https://data.montgomerycountymd.gov/Public-Safety/Traffic-Violations/4mse-ku6q/about_data
- Parking Inventory: https://data.montgomerycountymd.gov/Transportation/Parking-Garage-and-Lot-Inventory/rd7s-ntxu/about_data

In [9]:
# Upload Traffic Violations CSV
uploaded = files.upload()
tv_raw = pd.read_csv(io.BytesIO(list(uploaded.values())[0]), low_memory=False)

Saving Traffic_Violations_20260409 (1).csv to Traffic_Violations_20260409 (1).csv

In [10]:
# Upload Parking Inventory CSV
uploaded = files.upload()
park_raw = pd.read_csv(io.BytesIO(list(uploaded.values())[0]), low_memory=False)

Saving Parking_Garage_and_Lot_Inventory_20260409.csv to Parking_Garage_and_Lot_Inventory_20260409 (1).csv

## Inspect

In [11]:
tv_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 212173 entries, 0 to 212172
Data columns (total 43 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   SeqID                    212173 non-null  object
 1   Date Of Stop             212173 non-null  object
 2   Time Of Stop             212173 non-null  object
 3   Agency                   212173 non-null  object
 4   SubAgency                212173 non-null  object
 5   Description              212173 non-null  object
 6   Location                 212172 non-null  object
 7   Latitude                 212173 non-null  float64
 8   Longitude                212173 non-null  float64
 9   Accident                 212173 non-null  object
 10  Belts                    212173 non-null  object
 11  Personal Injury          212173 non-null  object
 12  Property Damage          212173 non-null  object
 13  Fatal                    212173 non-null  object
 14  Commercial License       212173 non-null  object
 15  HAZMAT                   212173 non-null  object
 16  Commercial Vehicle       212173 non-null  object
 17  Alcohol                  212173 non-null  object
 18  Work Zone                212173 non-null  object
 19  Search Conducted         132300 non-null  object
 20  Search Disposition       5555 non-null    object
 21  Search Outcome           132277 non-null  object
 22  Search Reason            5555 non-null    object
 23  Search Reason For Stop   132275 non-null  object
 24  Search Type              5555 non-null    object
 25  Search Arrest Reason     4541 non-null    object
 26  State                    212173 non-null  object
 27  VehicleType              212173 non-null  object
 28  Year                     211906 non-null  float64
 29  Make                     212167 non-null  object
 30  Model                    212163 non-null  object
 31  Color                    211500 non-null  object
 32  Violation Type           212173 non-null  object
 33  Charge                   212173 non-null  object
 34  Article                  204383 non-null  object
 35  Contributed To Accident  212173 non-null  bool
 36  Race                     212173 non-null  object
 37  Gender                   212173 non-null  object
 38  Driver City              212134 non-null  object
 39  Driver State             212173 non-null  object
 40  DL State                 212173 non-null  object
 41  Arrest Type              212173 non-null  object
 42  Geolocation              212173 non-null  object
dtypes: bool(1), float64(3), object(39)
memory usage: 68.2+ MB

In [12]:
tv_raw.head()

,SeqID,Date Of Stop,Time Of Stop,Agency,SubAgency,Description,Location,Latitude,Longitude,Accident,...,Charge,Article,Contributed To Accident,Race,Gender,Driver City,Driver State,DL State,Arrest Type,Geolocation
0,a7a56f3a-c671-488d-b08c-67dace2dd600,04/08/2026,10:24:00,MCP,"1st District, Rockville",EXCEEDING THE POSTED SPEED LIMIT OF 25 MPH,GEORGIA AVE @ REEDIE DR,39.040837,-77.051440,No,...,21-801.1,Transportation Article,False,ASIAN,F,SILVER SPRING,MD,MD,R - Unmarked Laser,"(39.0408366666667, -77.05144)"
1,5b6e4af1-dabf-47f3-ba18-6e64427e8df2,04/08/2026,10:24:00,MCP,Headquarters and Special Operations,DRIVER USING HANDS TO USE HANDHELD TELEPHONE W...,NEW HAMPSHIRE@ VITAL WAY,39.068618,-77.002878,No,...,21-1124.2(d2),Transportation Article,False,BLACK,F,WASHINGTON,DC,DC,A - Marked Patrol,"(39.0686181666667, -77.0028778333333)"
2,0b3eb0fc-011f-4914-b18e-577aa906dff0,04/08/2026,10:23:00,MCP,"5th District, Germantown",EXCEEDING THE POSTED SPEED LIMIT OF 40 MPH,NEW HAMPSHIRE AVE @ ELDRID DR,39.070309,-77.002954,No,...,21-801.1,Transportation Article,False,OTHER,M,SILVER SPRING,MD,MD,H - Unmarked Moving Radar (Stationary),"(39.070309, -77.0029538333333)"
3,0b3eb0fc-011f-4914-b18e-577aa906dff0,04/08/2026,10:23:00,MCP,"5th District, Germantown",OPERATING VEHICLE ON HIGHWAY WITH UNAUTHORIZED...,NEW HAMPSHIRE AVE @ ELDRID DR,39.070309,-77.002954,No,...,22-406(i1),Transportation Article,False,OTHER,M,SILVER SPRING,MD,MD,H - Unmarked Moving Radar (Stationary),"(39.070309, -77.0029538333333)"
4,7ce99f9f-0a48-4d72-8c20-0c29458ac4dd,04/08/2026,10:22:00,MCP,Headquarters and Special Operations,EXCEEDING POSTED MAXIMUM SPEED LIMIT: 39 MPH I...,GEORGIA / HIGHLAND,39.002668,-77.035511,No,...,21-801.1,Transportation Article,False,ASIAN,M,CLARKSBURG,MD,MD,Q - Marked Laser,"(39.0026685, -77.035511)"

In [13]:
# Missing values
tv_raw.isnull().sum()[tv_raw.isnull().sum() > 0].sort_values(ascending=False)

Search Arrest Reason      207632
Search Reason             206618
Search Type               206618
Search Disposition        206618
Search Reason For Stop     79898
Search Outcome             79896
Search Conducted           79873
Article                     7790
Color                        673
Year                         267
Driver City                   39
Model                         10
Make                           6
Location                       1
dtype: int64

In [14]:
park_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45 entries, 0 to 44
Data columns (total 35 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   District                      45 non-null     object
 1   Facility Number               45 non-null     object
 2   Address                       45 non-null     object
 3   Hours Requiring Payment       45 non-null     object
 4   Payment Options               45 non-null     object
 5   Floors                        45 non-null     int64
 6   Clearance Height (Feet)       45 non-null     int64
 7   Clearance Height (Inches)     45 non-null     int64
 8   Facility Name                 45 non-null     object
 9   Total Capacity                45 non-null     int64
 10  ADA Spaces                    45 non-null     int64
 11  ADA Van Spaces                45 non-null     int64
 12  Bike Spaces                   45 non-null     int64
 13  Car Spaces                    45 non-null     int64
 14  Motorcycle Spaces             45 non-null     int64
 15  Motorcycle Area               45 non-null     int64
 16  Other Information             0 non-null      float64
 17  Latitude                      45 non-null     float64
 18  Longitude                     45 non-null     float64
 19  5 Minute Limit                45 non-null     int64
 20  30 Minute Limit               45 non-null     int64
 21  1 Hour Limit                  45 non-null     int64
 22  2 Hour Limit                  45 non-null     int64
 23  3 Hour Limit                  45 non-null     int64
 24  4 Hour Limit                  45 non-null     int64
 25  9 Hour Limit                  45 non-null     int64
 26  12 Hour Limit                 45 non-null     int64
 27  15 Hour Limit                 45 non-null     int64
 28  Parking Convenience Stickers  45 non-null     int64
 29  Carpool                       45 non-null     int64
 30  Restricted                    45 non-null     int64
 31  Inactive                      45 non-null     bool
 32  Additional Information        45 non-null     object
 33  Last Update                   45 non-null     object
 34  Location                      45 non-null     object
dtypes: bool(1), float64(3), int64(22), object(9)
memory usage: 12.1+ KB

## Clean Traffic Violations

In [15]:
tv = tv_raw.copy()

# Column names
tv.columns = tv.columns.str.strip().str.lower().str.replace(' ', '_', regex=False)

# Parse dates and times
tv['date_of_stop'] = pd.to_datetime(tv['date_of_stop'], errors='coerce')
tv['time_of_stop'] = pd.to_datetime(tv['time_of_stop'], format='%H:%M:%S', errors='coerce').dt.time

# Temporal features
tv['year']        = tv['date_of_stop'].dt.year
tv['month']       = tv['date_of_stop'].dt.month
tv['month_name']  = tv['date_of_stop'].dt.month_name()
tv['day_of_week'] = tv['date_of_stop'].dt.day_name()
tv['hour']        = pd.to_datetime(tv['time_of_stop'].astype(str), format='%H:%M:%S', errors='coerce').dt.hour
tv['time_period'] = pd.cut(
    tv['hour'],
    bins=[-1, 4, 11, 16, 20, 23],
    labels=['Night', 'Morning', 'Afternoon', 'Evening', 'Night2']
)
tv['time_period'] = tv['time_period'].astype(str).replace('Night2', 'Night')

# Yes/No → 1/0
bool_cols = ['accident', 'belts', 'personal_injury', 'property_damage',
             'fatal', 'commercial_license', 'hazmat', 'commercial_vehicle',
             'alcohol', 'work_zone', 'search_conducted', 'contributed_to_accident']
for col in [c for c in bool_cols if c in tv.columns]:
    tv[col] = tv[col].map({'Yes': 1, 'No': 0})

# Standardize categoricals
for col in ['violation_type', 'race', 'gender', 'arrest_type', 'search_outcome']:
    if col in tv.columns:
        tv[col] = tv[col].astype(str).str.strip().str.title().replace({'Nan': np.nan})

# Fix bad coordinates
for col in ['latitude', 'longitude']:
    if col in tv.columns:
        tv[col] = pd.to_numeric(tv[col], errors='coerce')
        tv.loc[tv[col] == 0, col] = np.nan

# Filter
tv = tv.dropna(subset=['date_of_stop'])
tv = tv[tv['year'] >= 2018].reset_index(drop=True)

## Clean Parking Inventory

In [16]:
park = park_raw.copy()
park.columns = park.columns.str.strip().str.lower().str.replace(' ', '_', regex=False)
park = park.dropna(subset=['location']) if 'location' in park.columns else park

## Save to Google Drive

In [17]:
tv_raw.to_csv(os.path.join(BASE, 'data/raw/traffic_violations_raw.csv'), index=False)
park_raw.to_csv(os.path.join(BASE, 'data/raw/parking_inventory_raw.csv'), index=False)
tv.to_csv(os.path.join(BASE, 'data/processed/traffic_violations_clean.csv'), index=False)
park.to_csv(os.path.join(BASE, 'data/external/parking_inventory_clean.csv'), index=False)

## Check

In [18]:
tv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 212173 entries, 0 to 212172
Data columns (total 48 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   seqid                    212173 non-null  object
 1   date_of_stop             212173 non-null  datetime64[ns]
 2   time_of_stop             212173 non-null  object
 3   agency                   212173 non-null  object
 4   subagency                212173 non-null  object
 5   description              212173 non-null  object
 6   location                 212172 non-null  object
 7   latitude                 182076 non-null  float64
 8   longitude                182076 non-null  float64
 9   accident                 212173 non-null  int64
 10  belts                    212173 non-null  int64
 11  personal_injury          212173 non-null  int64
 12  property_damage          212173 non-null  int64
 13  fatal                    212173 non-null  int64
 14  commercial_license       212173 non-null  int64
 15  hazmat                   212173 non-null  int64
 16  commercial_vehicle       212173 non-null  int64
 17  alcohol                  212173 non-null  int64
 18  work_zone                212173 non-null  int64
 19  search_conducted         132300 non-null  float64
 20  search_disposition       5555 non-null    object
 21  search_outcome           132277 non-null  object
 22  search_reason            5555 non-null    object
 23  search_reason_for_stop   132275 non-null  object
 24  search_type              5555 non-null    object
 25  search_arrest_reason     4541 non-null    object
 26  state                    212173 non-null  object
 27  vehicletype              212173 non-null  object
 28  year                     212173 non-null  int32
 29  make                     212167 non-null  object
 30  model                    212163 non-null  object
 31  color                    211500 non-null  object
 32  violation_type           212173 non-null  object
 33  charge                   212173 non-null  object
 34  article                  204383 non-null  object
 35  contributed_to_accident  0 non-null       float64
 36  race                     212173 non-null  object
 37  gender                   212173 non-null  object
 38  driver_city              212134 non-null  object
 39  driver_state             212173 non-null  object
 40  dl_state                 212173 non-null  object
 41  arrest_type              212173 non-null  object
 42  geolocation              212173 non-null  object
 43  month                    212173 non-null  int32
 44  month_name               212173 non-null  object
 45  day_of_week              212173 non-null  object
 46  hour                     212173 non-null  int32
 47  time_period              212173 non-null  object
dtypes: datetime64[ns](1), float64(4), int32(3), int64(10), object(30)
memory usage: 75.3+ MB

In [19]:
tv['violation_type'].value_counts()

violation_type
Warning     143121
Citation     61262
Esero         7790
Name: count, dtype: int64

In [20]:
tv['year'].value_counts().sort_index()

year
2024     80066
2025    101749
2026     30358
Name: count, dtype: int64